sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

cache:
  - composer
  - $HOME/.composer/cache

php:
  - 5.3
  - 5.6
  - 7.1

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=3.7 WP_MULTISITE=0
  - WP_VERSION=4.7.2 WP_MULTISITE=0

matrix:
  include:
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=1 SNIFF=1

before_script:
  - if [[ "$SNIFF" == "1" ]]; then export PATH="$HOME/.composer/vendor/bin:$PATH"; fi
  - if [[ "$SNIFF" == "1" ]]; then composer global require wp-coding-standards/wpcs; fi
  - if [[ "$SNIFF" == "1" ]]; then phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs; fi

script:
  # Search theme for PHP syntax errors.
  - find . \( -name '*.php' \) -exec php -lf {} \;
  - if [[ "$SNIFF" == "1" ]]; then phpcs --standard=phpcs.ruleset.xml $(find . -name '*.php'); fi
  - if [[ "$SNIFF" == "1" ]]; then phpcs --standard=phpcs.ruleset.xml $(find . -name '*.php'); fi
