dist: trusty

cache:
  apt: true
  directories:
    # Cache directory for older Composer versions.
    - $HOME/.composer/cache/files
    # Cache directory for more recent Composer versions.
    - $HOME/.cache/composer/files

language: php

php:
  - 7.0
  - 7.1
  - 7.3
  - nightly

 env:
  # Highest supported PHPCS version.
  - PHPCS_BRANCH="dev-master" LINT=1
  # Lowest supported PHPCS version.
  - PHPCS_BRANCH="3.3.0"

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - development

matrix:
  fast_finish: true
  include:
    # Seperate builds for PHP 7.2 with additional checks.
    - php: 7.2
      env: PHPCS_BRANCH="dev-master" LINT=1 SNIFF=1
      addons:
        apt:
          packages:
            - libxml2-utils
    - php: 7.2
      env: PHPCS_BRANCH="3.3.0"

  allow_failures:
    # Allow failures for unstable builds.
    - php: nightly
    - php: 7.3
      env: PHPCS_BRANCH="3.3.0"

before_install:
  - phpenv config-rm xdebug.ini
  - composer require squizlabs/php_codesniffer:${PHPCS_BRANCH} --no-update --no-suggest --no-scripts

script:
  # Lint the PHP files against parse errors.
  - if [[ "$LINT" == "1" ]]; then if find . -path ./vendor -prune -o -name "*.php" -exec php -l {} \; | grep "^[Parse error|Fatal error]"; then exit 1; fi; fi
  # Check the codestyle of the WPThemeReview codebase.
  - if [[ "$SNIFF" == "1" ]]; then $(pwd)/vendor/bin/phpcs; fi
