sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

cache:
  - composer
  - $HOME/.composer/cache

php:
  - 5.2
  - 5.6
  - 7.1

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=3.7 WP_MULTISITE=0
  - WP_VERSION=4.7.2 WP_MULTISITE=0

matrix:
  include:
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=1 SNIFF=1

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require wp-coding-standards/wpcs
  - phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs

script:
  - if [[ "$SNIFF" == "1" ]]; then phpcs --standard=phpcs.ruleset.xml $(find . -name '*.php'); fi
